### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/driving-game#1]
<img width="860" alt="68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7365652d74686569722d6361722e706e67" src="https://user-images.githubusercontent.com/52344883/108413096-d16e8f80-71e7-11eb-8ea4-f448a60606cb.png">

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML, JS, and CSS files
- [x] Change background color of window to green
- [x] Add a container to hold car
- [x] Fit car in container
