### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] In the main.js file add query selector for the car image
- [x] Add event listeners for right and left arrow clicks
- [x] Car rotates to point toward clicked arrow direction
