### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to the data model to hold the car's x,y coordinates
- [x] Apply absolute positioning on the image
- [x] Using the style property of the element set the top and left offsets
- [x] Add a space button event listener
- [x] Set interval and move the car a few pixels every 16 milliseconds
