### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] create a counter for spacebar keydowns
- [x] create a variable for the interval
- [x] if its odd interval start if not interval stop
